spring.application.name=journalApp
spring.mongodb.uri=mongodb+srv://krishna1myadav_db_user:010101KmyDb@cluster0.wstd54m.mongodb.net/journaldb?retryWrites=true&w=majority&tls=true
#spring.data.mongodb.username=
#spring.data.mongodb.password=
spring.data.mongodb.auto-index-creation=true

